### ISSUE TITLE
Creation of base anchors if none

### ISSUE THREAD

**Issue by fr4nzap** [fr4nzap/zapthreads#10]

**Comment by verbiricha** [comment]
You planning to support regular URLs too? I think NoComment uses `r` tags but haven't checked, would be cool if zapthreads supports nostr and non nostr commenting imo.

**Comment by fr4nzap** [comment]
Yes, URLs are already supported via `r` tags. In the repo there is an `embedded.html` showing this.

The issue right now is it will only work if there already were anchor tags (like in the case of https://fiatjaf.com/nostr.html ) but not for new URLs.
