### ISSUE TITLE
Embed link

### ISSUE THREAD

**Issue by nima1981** [fr4nzap/zapthreads#41]
Is there a hosted link to embed this script on a website like nocomment has?

**Comment by fr4nzap** [comment]
Okay I think I see the problem, you're trying to use it with `data-*` attributes like nocomment and that doesn't work here. Just import the script, and then use like here: https://github.com/21ideas-org/21ideas.org/blob/e06d11719b73d728020a409d0b82caa2dcdec34f/themes/hugo-book/layouts/partials/docs/comments.html#L5

**Comment by nima1981** [comment]
Is there any reason why the whole plugin doesn’t show up on my mobile device?Sent from my iPhoneOn Nov 27, 2023, at 12:54 PM, franzap ***@***.***> wrote:﻿
Okay I think I see the problem, you're trying to use it with data-* attributes like nocomment and that doesn't work here. Just import the script, and then use like here: https://github.com/21ideas-org/21ideas.org/blob/e06d11719b73d728020a409d0b82caa2dcdec34f/themes/hugo-book/layouts/partials/docs/comments.html#L5
