### ISSUE TITLE
The comments section doesn't show up on my mobile device.

### ISSUE THREAD

**Issue by nima1981** [fr4nzap/zapthreads#42]
![image0(8)](https://github.com/fr4nzap/zapthreads/assets/10733323/beb0c7d4-1e77-47c3-851b-531c53173336)

see: https://dissentwatch.com/boost/?boost_post_id=668155
Tried with Chrome, Firefox on iPhone.

**Comment by fr4nzap** [comment]
Tried on mobile and it's working. If you still have issues please reopen!
