### ISSUE TITLE
Support empty d tags in naddr anchors

### ISSUE THREAD

**Issue by verbiricha** [fr4nzap/zapthreads#45]
Anchors for naddrs with empty `d` tags throw an error (for example `naddr1qqqqygq8qs0rcr5gd2n8gchwwh8eawjwfxwfd9klaajmtcxx6cff2jyz8vpsgqqqw4rslmrjpc`). Is an error in `nostr-tools`, Habla had this issue and upgrading solved it.

**Comment by fr4nzap** [comment]
Thanks man, will upgrade to `nostr-tools` when I get to this in the next few days
