### ISSUE TITLE
Be more explicit with the relays that have received the comment

### ISSUE THREAD

**Issue by verbiricha** [fr4nzap/zapthreads#46]
A user found that the feedback when not being able to send the event to all relays was insufficient, reported here https://github.com/verbiricha/habla.news/issues/160

**Comment by fr4nzap** [comment]
Done! @verbiricha can you update habla.news to zapthreads `0.5.1`? it has a bunch of fixes and on the latest `nostr-tools`

**Comment by verbiricha** [comment]
Thanks Fran! Works perfectly.
